// User
export const GOOGLE_SINGIN_START = 'GOOGLE_SINGIN_START';
export const EMAIL_SINGIN_START = 'EMAIL_SINGIN_START';

export const SINGIN_SUCCESS = 'SINGIN_SUCCESS';
export const SINGIN_FAILED = 'SINGIN_FAILED';

export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';

export const SINGOUT_START = 'SINGOUT_START';
export const SINGOUT_SUCCESS = 'SINGOUT_SUCCESS';
export const SINGOUT_FAILED = 'SINGOUT_FAILED';

export const SINGUP_START = 'SINGUP_START';
export const SINGUP_SUCCESS = 'SINGUP_SUCCESS';
export const SINGUP_FAILED = 'SINGUP_FAILED';
// Cart
export const TOOGLE_SHOW_CART = 'TOOGLE_SHOW_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CARD = 'REMOVE_TO_CARD';
export const CLEAR_ITEM_TO_CARD = 'CLEAR_ITEM_TO_CARD';
export const CLEAR_ALL_CARD = 'CLEAR_ALL_CARD';
export const SET_CART_FROM_FIREBASE = 'SET_CART_FROM_FIREBASE';
export const UPDATE_CART_IN_FIREBASE = 'UPDATE_CART_IN_FIREBASE';
// Shop
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILED = 'FETCH_COLLECTIONS_FAILED';